name: Build and release Git-Mastery CLI for Linux

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-release:
    permissions:
      contents: write
      pull-requests: write
      packages: read
      issues: read

    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build binary
        run: |
          pyinstaller gitmastery.spec

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/gitmastery
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
